# Generated by Django 6.0.6 on 2026-06-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("content", models.TextField(verbose_name="متن اعلان")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "show_on_login",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در صفحه لاگین"
                    ),
                ),
                (
                    "show_on_dashboard",
                    models.BooleanField(default=True, verbose_name="نمایش در داشبورد"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
