# Generated by Django 5.2.1 on 2026-06-04 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان دوره")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("instructor", models.CharField(max_length=100, verbose_name="مدرس")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="ظرفیت"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان محتوا")),
                (
                    "content_type",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("Video", "ویدئو"), ("Text", "متن")],
                        default="PDF",
                        max_length=10,
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contents/%Y/%m/",
                        verbose_name="فایل",
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="محتوای متنی"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="ترتیب")),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="مدت زمان (برای ویدئو)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ بارگذاری"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="academy.course",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="شماره تماس"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "enrolled_courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="students",
                        to="academy.course",
                        verbose_name="دوره\u200cهای ثبت\u200cنام شده",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
    ]
