# Generated by Django 6.0.6 on 2026-06-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام رویداد"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.eventtype",
                verbose_name="نوع رویداد",
            ),
            preserve_default=False,
        ),
    ]
